config-version: 1.4

#Containers to make portable
portable-barrels: true
portable-blast-furnaces: true
portable-brewing-stands: true
portable-chests: true
portable-dispensers: true
portable-droppers: true
portable-furnaces: true
portable-hoppers: true
portable-smokers: true

#Can containers stack when they have exactly the same content?
allow-stacking: false

#Should the container drop its content as it normally would if the player is sneaking?
sneaky-break-drops: true

#1 for container inside a container, 2 for container inside a container inside a container, so on...
max-nesting: 0

#Same thing but for shulker boxes
shulker-max-nesting: 0

#Message sent to the player when the nesting limit is reached
nesting-limit-message: §cNesting limit reached!

#Penalties (PotionEffectType) to apply when a player holds a portable container in their inventory
#Shulker boxes won't cause this unless they contain a portable container
#Check https://jd.papermc.io/paper/1.21.4/org/bukkit/potion/PotionEffectType.html
# !! CHANGE 1.21.4 IN THE LINK ABOVE WITH YOUR SERVER VERSION !!
#Format: <EFFECT>: <LEVEL>
penalties:
#-- Example for 1.21.4 --
  SLOWNESS: 1
  MINING_FATIGUE: 0

#The higher the number, the longer the penalties will last
penalty-duration: 50 #ticks

#The lower the number, the faster the penalties will be updated
# !! MAY INDUCE LAGS IF TOO LOW !!
penalty-update: 25 #ticks

#The enchantment required on the handling tool to create a portable container (one only enchantment supported)
#Check https://jd.papermc.io/paper/1.21.4/org/bukkit/enchantments/Enchantment.html
# !! CHANGE 1.21.4 IN THE LINK ABOVE WITH YOUR SERVER VERSION !!
#Format: <ENCHANTMENT>: <LEVEL>
enchantment-required:
#-- Example for 1.21.4 --
#  SILK_TOUCH: 1

#Should the plugin ignore items with custom names? If not they will be portable too
ignore-custom-named: false

#The worlds where portable containers can be created in
create-in-worlds:
  - world
  - nether
  - end

#The worlds where portable containers can be placed in
place-in-worlds:
  - world
  - nether
  - end

#Message sent to the player when they cannot place a container in that world
world-cannot-place-message: §cYou cannot place a portable container in this world!

#Only for 1.21.4+
#Can portable containers be stored in bundles?
#Allows 64 CONTAINERS in every bundle and bundles inside containers, are you sure it's a good idea?
allow-bundles: false

#Only for 1.21.4+
#Message sent to the player when they cannot place a container in a bundle
bundle-cannot-place-message: §cYou cannot place a portable container in a bundle!