name: PortableChests
version: ${project.version}
main: cyanogenoid.portablechests.PortableChests
api-version: 1.16
authors: [ Cyanogenoid ]
description: Portable chests, barrels, hoppers..

permissions:
  cyanogenoid.portablechests.create:
    description: Grants the permission to make containers portable when broken
    default: true

